import {
  siReact, siNodedotjs, siFigma, siPostgresql, siGo, siTypescript,
  siDocker, siVuedotjs, siPython, siRust, siSvelte, siGraphql,
  siRedis, siHtml5, siTailwindcss, siKubernetes, siMongodb, siSwift,
  siKotlin, siGit, siGithub, siJavascript,
  siDotnet, siNginx, siUnrealengine, siGnubash, siGitforwindows, siEslint,
  siPastebin, siDevelopmentcontainers, siPagespeedinsights,
  siMaterialdesignicons, siUml, siAngular, siPypi, siRedux, siSupabase,
  siOpenjdk, siMariadbfoundation, siWebassembly, siSwagger, siElectron,
  siSass, siCplusplus, siCmake
} from 'simple-icons';

const getRandomFloat = (): { tx1: string; ty1: string; tx2: string; ty2: string; duration: string } => ({
  tx1: `${String(Math.floor(Math.random() * 80 - 40))}px`,
  ty1: `${String(Math.floor(Math.random() * 80 - 40))}px`,
  tx2: `${String(Math.floor(Math.random() * 80 - 40))}px`,
  ty2: `${String(Math.floor(Math.random() * 80 - 40))}px`,
  duration: `${String(Math.floor(Math.random() * 40 + 40))}s`,
});

export const heroTechnologies = [
  { name: 'React', icon: siReact, color: '#61DAFB', top: '15%', left: '80%', delay: '0s' },
  { name: 'Node.js', icon: siNodedotjs, color: '#339933', top: '35%', left: '70%', delay: '1.2s' },
  { name: 'Figma', icon: siFigma, color: '#F24E1E', top: '80%', left: '75%', delay: '2.5s' },
  { name: 'PostgreSQL', icon: siPostgresql, color: '#336791', top: '65%', left: '85%', delay: '0.8s' },
  { name: 'Go', icon: siGo, color: '#00ADD8', top: '20%', left: '60%', delay: '1.8s' },
  { name: 'TypeScript', icon: siTypescript, color: '#3178C6', top: '55%', left: '90%', delay: '0.5s' },
  { name: 'Docker', icon: siDocker, color: '#2496ED', top: '85%', left: '60%', delay: '2.1s' },
  { name: 'Vue', icon: siVuedotjs, color: '#4FC08D', top: '12%', left: '10%', delay: '1.5s' },
  { name: 'Python', icon: siPython, color: '#3776AB', top: '85%', left: '15%', delay: '0.2s' },
  { name: 'Rust', icon: siRust, color: '#DEA584', top: '45%', left: '82%', delay: '0.9s' },
  { name: 'Svelte', icon: siSvelte, color: '#FF3E00', top: '50%', left: '60%', delay: '1.1s' },
  { name: 'GraphQL', icon: siGraphql, color: '#E10098', top: '25%', left: '35%', delay: '0.3s' },
  { name: 'Redis', icon: siRedis, color: '#DC382D', top: '75%', left: '40%', delay: '2.2s' },
  { name: 'HTML5', icon: siHtml5, color: '#E34F26', top: '80%', left: '30%', delay: '1.7s' },
  { name: 'Kubernetes', icon: siKubernetes, color: '#326CE5', top: '28%', left: '88%', delay: '2.8s' },
  { name: 'MongoDB', icon: siMongodb, color: '#47A248', top: '10%', left: '45%', delay: '0.6s' },
  { name: 'Swift', icon: siSwift, color: '#F05138', top: '88%', left: '90%', delay: '1.9s' },
  { name: 'Kotlin', icon: siKotlin, color: '#7F52FF', top: '70%', left: '10%', delay: '0.4s' },
  { name: 'Git', icon: siGit, color: '#F05032', top: '40%', left: '20%', delay: '0.7s' },
  { name: 'GitHub', icon: siGithub, color: '#181717', top: '60%', left: '25%', delay: '1.4s' },
  { name: 'Tailwind CSS', icon: siTailwindcss, color: '#06B6D4', top: '20%', left: '25%', delay: '2.0s' },
  { name: 'JavaScript', icon: siJavascript, color: '#F7DF1E', top: '50%', left: '5%', delay: '1.0s' },
  { name: '.NET', icon: siDotnet, color: '#512BD4', top: '18%', left: '48%', delay: '3.1s' },
  { name: 'NGINX', icon: siNginx, color: '#009639', top: '85%', left: '45%', delay: '1.6s' },
  { name: 'Unreal Engine', icon: siUnrealengine, color: '#0E1128', top: '35%', left: '5%', delay: '2.4s' },
  { name: 'GNU Bash', icon: siGnubash, color: '#4EAA25', top: '60%', left: '10%', delay: '0.9s' },
  { name: 'Git for Windows', icon: siGitforwindows, color: '#F05032', top: '28%', left: '12%', delay: '1.3s' },
  { name: 'ESLint', icon: siEslint, color: '#4B32C3', top: '72%', left: '30%', delay: '3.0s' },
  { name: 'Pastebin', icon: siPastebin, color: '#02456C', top: '42%', left: '90%', delay: '2.7s' },
  { name: 'Dev Containers', icon: siDevelopmentcontainers, color: '#2496ED', top: '65%', left: '45%', delay: '1.1s' },
  { name: 'PageSpeed Insights', icon: siPagespeedinsights, color: '#E94235', top: '15%', left: '38%', delay: '0.8s' },
  { name: 'Material Design', icon: siMaterialdesignicons, color: '#2196F3', top: '88%', left: '60%', delay: '2.5s' },
  { name: 'UML', icon: siUml, color: '#000000', top: '30%', left: '80%', delay: '1.2s' },
  { name: 'Angular', icon: siAngular, color: '#DD0031', top: '48%', left: '15%', delay: '0.4s' },
  { name: 'PyPI', icon: siPypi, color: '#3775A9', top: '78%', left: '10%', delay: '2.2s' },
  { name: 'Redux', icon: siRedux, color: '#764ABC', top: '35%', left: '28%', delay: '1.9s' },
  { name: 'Supabase', icon: siSupabase, color: '#3ECF8E', top: '55%', left: '72%', delay: '0.6s' },
  { name: 'OpenJDK', icon: siOpenjdk, color: '#437291', top: '90%', left: '20%', delay: '1.7s' },
  { name: 'MariaDB', icon: siMariadbfoundation, color: '#003545', top: '40%', left: '38%', delay: '3.3s' },
  { name: 'WebAssembly', icon: siWebassembly, color: '#654FF0', top: '22%', left: '72%', delay: '2.6s' },
  { name: 'Swagger', icon: siSwagger, color: '#85EA2D', top: '68%', left: '55%', delay: '1.4s' },
  { name: 'Electron', icon: siElectron, color: '#47848F', top: '12%', left: '55%', delay: '0.3s' },
  { name: 'Sass', icon: siSass, color: '#CC6699', top: '75%', left: '60%', delay: '2.9s' },
  { name: 'C++', icon: siCplusplus, color: '#00599C', top: '45%', left: '55%', delay: '0.5s' },
  { name: 'CMake', icon: siCmake, color: '#064F8C', top: '82%', left: '5%', delay: '1.8s' }
].map(tech => ({ ...tech, ...getRandomFloat() }));
