export { ProjectCard, type ProjectCardProps } from './ui/ProjectCard/ProjectCard'
export { ProjectCardSkeleton } from './ui/ProjectCardSkeleton/ProjectCardSkeleton'
export type { IProject } from './model/IProject'
export type { IProjectSlot, IProjectSlotSkill } from './model/IProjectSlot'
export { fetchProjectById, fetchProjectSlots, type IProjectDetailResponse } from './api/projectApi'
