services:
    db:
        image: postgres:15-alpine
        restart: always
        env_file:
            - .env.stand
        volumes:
            - db_data:/var/lib/postgresql/data
        command: -p 5700
        ports:
            - "5700:5700"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "psql -U $${POSTGRES_USER} -p 5700 -d $${POSTGRES_DB} -c 'SELECT 1' || exit 1",
                ]
            interval: 5s
            timeout: 2s
            retries: 10

    api:
        build: .
        restart: on-failure
        depends_on:
            - db
        env_file:
            - .env.stand
        ports:
            - "8900:8900"
        expose:
          - '8900'

volumes:
    db_data:
        driver: local
