FROM oven/bun:1.3

RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p /root/.bun/install/cache

COPY package.json bun.lock ./

RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install


COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev"]