services:
    scalar:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html:ro
            - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
